<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/08/31 18:14:51

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
